# Generated by Django 4.2.7 on 2023-12-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_created_0e6ed4_idx',
        ),
    ]
